spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/local
    username: postgres
    password: 1234
    driver: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update

server:
  port : 8092
